image: python:3.7

before_script:
  - apt-get install -y pip
  - pip install Django
  - pip install -r requirements.txt

stages:
  - development
  - test

test:
  script:
    - python src/manage.py test
