version: '3.7'

services:
  db:
    image: postgres
  web:
    build: .
      command: python src/manage.py runserver 0.0.0.0:0000
      volumes:
        - .:/src
      ports:
        - "8000:8000"
      depends_on:
        - db