# Generated by Django 2.2.10 on 2020-02-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notification_date',
        ),
    ]
