# Generated by Django 2.2.10 on 2020-02-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200216_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'White'), (2, 'Blue'), (3, 'Red'), (4, 'Yellow')], default=1),
        ),
    ]
