# Generated by Django 2.2.10 on 2020-02-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200217_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expected_end_date',
        ),
    ]
